import type { Metadata } from 'next';
import { Darker_Grotesque } from 'next/font/google';

import './globals.css';

const grotes_dark = Darker_Grotesque(
  {
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    variable: '--font-grotes_dark',
  });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={grotes_dark.variable}>{children}</body>
    </html>
  );
}
